Feature: NameParser

This API will take strings and place them into the Individual or Entity depending on the way it's written


Scenario: Parse names into Individual or Entity
	Given I get access token for Account Verification
	When I pass in array of <names>
	Then I expect the names to be separeted into Individual or Entity and has expected <amount> of objects

Examples: 
| amount | names                                                                                                                                                                                                                                                                           |
| 1      | Donald Duck                                                                                                                                                                                                                                                                     |
| 1      | Mr. Donald Duck                                                                                                                                                                                                                                                                 |
| 1      | Donald Duck III                                                                                                                                                                                                                                                                 |
| 1      | Mr. Edward Horseface III                                                                                                                                                                                                                                                        |
| 1      | Donald Duck, Inc                                                                                                                                                                                                                                                                |
| 1      | Donald Duck, LLC                                                                                                                                                                                                                                                                |
| 3      | Donald Duck, Daffy Duck, Duck & Sons, Inc.                                                                                                                                                                                                                                      |
| 2      | Donald Duck and Daffy Duck                                                                                                                                                                                                                                                      |
| 2      | Donald and Daffy Duck                                                                                                                                                                                                                                                           |
| 1      | The Donald Duck Trust                                                                                                                                                                                                                                                           |
| 1      | Duck & Duck & Duck, LLC                                                                                                                                                                                                                                                         |
| 1      | Donald Duck, esq                                                                                                                                                                                                                                                                |
| 1      | Mr. Donald Duck, MD                                                                                                                                                                                                                                                             |
| 1      | Mr Edward Horseface III                                                                                                                                                                                                                                                         |
| 2      | Jim and Jane Doe                                                                                                                                                                                                                                                                |
| 3      | John and Jill Black, A married couple                                                                                                                                                                                                                                           |
| 1      | Google                                                                                                                                                                                                                                                                          |
| 1      | The Best Bank Ever                                                                                                                                                                                                                                                              |
| 1      | Rooster, Inc                                                                                                                                                                                                                                                                    |
| 2      | Mr Santa T Claus, III and Miss Snow S Claus, Esq                                                                                                                                                                                                                                |
| 6      | Thomas Wayne, M.D., Lee Yeon Suk, Ana Lorena López Ramírez, Wen Jiabao xiān sheng, Mr. Oswald Cobblepot, Maria Andujo Melandez de Lopez                                                                                                                                         |
| 1      | Charles Pennington III                                                                                                                                                                                                                                                          |
| 1      | Miss Mary Jones                                                                                                                                                                                                                                                                 |
| 3      | Mr James T Jones and Miss Mary S Jones, Esq, This Is My Another Dream Company                                                                                                                                                                                                   |
| 1      | Miss Mary S Jones, Esq                                                                                                                                                                                                                                                          |
| 1      | Mary S Jones, Esq                                                                                                                                                                                                                                                               |
| 1      | Mary Jones, Esq                                                                                                                                                                                                                                                                 |
| 2      | Mary Jones, AbaraCadabra                                                                                                                                                                                                                                                        |
| 2      | Mary Jones and Tom Jones                                                                                                                                                                                                                                                        |
| 3      | Mary Jones, Tom and Smith Jones                                                                                                                                                                                                                                                 |
| 3      | Mary Jones, Tom Jones, Frank Sinatra                                                                                                                                                                                                                                            |
| 2      | John and Jay Doe                                                                                                                                                                                                                                                                |
| 2      | Mickey Mouse, Disney & Orlando and Mini                                                                                                                                                                                                                                         |
| 2      | Foo And Bar, Donkey & Tiger and Mini                                                                                                                                                                                                                                            |
| 1      | CareHere, LLC                                                                                                                                                                                                                                                                   |
| 1      | Morgan & Morgan, INC                                                                                                                                                                                                                                                            |
| 4      | Mary Jones, Morgan & Morgan, INC, John and Jay Daoe                                                                                                                                                                                                                             |
| 18     | Mary Jones, John And James and Jane Daoe AND Sam A Smith, Shawn Daley & Mika Bayramov And Joey Yip Man, Morgan & Morgan, INC, John and Jay Abc, CareHere, LLC, Mr Smith Trust, Chase Mortgage Bank, Hampton Springs HOA, Mr Cooper, Lender Company, This My Dream Business, Inc |
| 4     | Jr. Bonnie Gracia, Miss James Gracia, Jr Bonnie Gracia, Md James Gracia|
